API_SERVICE_NAME = "youtube"
API_VERSION = "v3"
YT_CLIENT_SECRET = "data/client_secret.json"
YT_MANAGE_SCOPE = "https://www.googleapis.com/auth/youtube"
YT_LIST_RETURN = "status, contentDetails"
YT_AUTH_FILE = "data/yt_auth_token.pickle"
YT_DATAFOLDER = "data/"
YT_DATAFILE = "yt-playlist.txt"